services:
  dev_container:
    build:
      # context: where should docker compose look for the Dockerfile?
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    environment:
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1
      BUILDKIT_INLINE_CACHE: 1
    volumes:
      # Mount the repo folder contents into the container so we can use the code.
      - .:/workspace:cached
      # Mount the Docker socket so we can build images from within the container.
      - /var/run/docker.sock:/var/run/docker.sock
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity